apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: hello-nginx2
          image: nginx:latest
          ports:
            - containerPort: 80
