apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    test: deploy
  name: testpod
spec:
  containers:
  - image: kett/web:v1
    imagePullPolicy: IfNotPresent
    name: testpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
