apiVersion: v1
kind: Service
metadata:
  name: my-svc-np
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80           # 서비스를 노출하는 포트
      targetPort: 8080   # 파드를 노출하는 포트
      nodePort: 30080
