apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deploy
  annotations:
    kubernetes.io/change-cause: "update image version 2 to 3"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: basic-container
          image: kett/web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
